# Generated by Django 6.0 on 2026-09-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_cameraconfiguration_success_sound_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='finger_type',
            field=models.CharField(blank=True, default='Right Index', help_text='Designation of scanned finger (e.g., Right Index, Right Thumb)', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='fingerprint_data',
            field=models.TextField(blank=True, help_text='Biometric ridge minutiae pattern data', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fingerprint_id',
            field=models.CharField(blank=True, help_text='Unique biometric fingerprint ID / hash', max_length=255, null=True, unique=True),
        ),
    ]
